<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Gauravs-MacBook-Air.local" failures="2" tests="4" name="PetTests" time="15.303" errors="0" timestamp="2025-06-26T09:59:51 IST">
  <testcase classname="api.test.UserTests2" name="testPostUser" time="2.785"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.69">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testGetUserByName(UserTests2.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests2" name="testUpdateUserByName" time="3.672">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testUpdateUserByName(UserTests2.java:88)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUserByName -->
  <testcase classname="api.test.UserTests2" name="testDeleteUserByName" time="1.738"/>
</testsuite> <!-- PetTests -->
